export const LOCALITIES = [
  {
    id: 'koramangala',
    name: 'Koramangala',
    zone: 'South',
    mapX: 52,
    mapY: 60,
    tag: 'Startup & hip',
    tagline: 'The city\'s beating startup heart',
    income: {
      jobScore: 82,
      freelanceScore: 91,
      avgSalaryLPA: { min: 18, max: 38 },
      topEmployers: ['Swiggy', 'Zepto', 'Meesho', 'Razorpay', 'CRED'],
      topRoles: ['Product Manager', 'Software Engineer', 'Design', 'Growth', 'Finance'],
      freelanceRate: '₹3–15k/day',
    },
    invest: {
      resScore: 72,
      comScore: 65,
      pricePerSqft: 17000,
      appreciation: 14.7,
      rentalYield: 3.2,
      avgPropertyPrice: 145,
      breakEvenYrs: 10,
      topProjects: ['Prestige Pinewood', 'Embassy Meadows', 'GP Aditya'],
    },
    lifestyle: {
      foodScore: 96,
      clothScore: 88,
      nightlifeScore: 95,
      foodRange: '₹80–2500/meal',
      clothRange: '₹800–8k/visit',
      vibe: 'Hip, startup-dense, never sleeps',
      topSpots: ['Toast & Tonic', 'Truffles', 'Byg Brewski', 'Third Wave Coffee'],
    },
    rent: { studio: 22, oneBHK: 28, twoBHK: 42, threeBHK: 75 },
    commute: {
      indiranagar: 15,
      hsr: 12,
      whitefield: 70,
      electronicCity: 30,
      mgRoad: 25,
    },
    metro: 'Silk Board (2.7km) — Yellow Line',
    summary: 'Rent here for the lifestyle and career network. Invest elsewhere for ROI.',
  },
  {
    id: 'whitefield',
    name: 'Whitefield',
    zone: 'East',
    mapX: 82,
    mapY: 50,
    tag: 'IT hub',
    tagline: 'India\'s largest IT employment cluster',
    income: {
      jobScore: 96,
      freelanceScore: 55,
      avgSalaryLPA: { min: 14, max: 28 },
      topEmployers: ['Accenture', 'SAP Labs', 'IBM', 'Capgemini', 'Infosys BPO'],
      topRoles: ['Software Engineer', 'DevOps', 'Data', 'Product', 'Finance'],
      freelanceRate: '₹1.5–6k/day',
    },
    invest: {
      resScore: 78,
      comScore: 82,
      pricePerSqft: 9000,
      appreciation: 19,
      rentalYield: 4.1,
      avgPropertyPrice: 90,
      breakEvenYrs: 7,
      topProjects: ['Godrej Splendour', 'Prestige Tech Vista', 'ITPL residences'],
    },
    lifestyle: {
      foodScore: 58,
      clothScore: 62,
      nightlifeScore: 40,
      foodRange: '₹250–1200/meal',
      clothRange: '₹600–4k/visit',
      vibe: 'IT campus town, mall-centric, quiet nights',
      topSpots: ['Phoenix Marketcity', 'Forum Value Mall', 'The Fatty Bao'],
    },
    rent: { studio: 16, oneBHK: 20, twoBHK: 30, threeBHK: 50 },
    commute: {
      indiranagar: 50,
      hsr: 60,
      whitefield: 0,
      electronicCity: 75,
      mgRoad: 55,
    },
    metro: 'Purple Line — Kadugodi to Indiranagar (37 min)',
    summary: 'Best for IT careers and property investment. Lifestyle is mall-dependent.',
  },
  {
    id: 'electronic_city',
    name: 'Electronic City',
    zone: 'South',
    mapX: 52,
    mapY: 82,
    tag: 'IT manufacturing',
    tagline: 'Campus-scale IT & best property value',
    income: {
      jobScore: 88,
      freelanceScore: 42,
      avgSalaryLPA: { min: 8, max: 20 },
      topEmployers: ['Infosys', 'Wipro', 'HCL', 'Tech Mahindra', 'Bharat Electronics'],
      topRoles: ['Software Engineer', 'QA', 'DevOps', 'Data', 'Manufacturing'],
      freelanceRate: '₹1–4k/day',
    },
    invest: {
      resScore: 84,
      comScore: 60,
      pricePerSqft: 6500,
      appreciation: 21,
      rentalYield: 4.8,
      avgPropertyPrice: 65,
      breakEvenYrs: 6,
      topProjects: ['SNN Raj Serenity', 'Prestige Tech Vista', 'Sobha units'],
    },
    lifestyle: {
      foodScore: 44,
      clothScore: 38,
      nightlifeScore: 20,
      foodRange: '₹60–600/meal',
      clothRange: '₹400–2k/visit',
      vibe: 'Budget-friendly, campus life, limited nightlife',
      topSpots: ['Darshini chains', 'Campus canteens', 'Forum Mall (drive)'],
    },
    rent: { studio: 12, oneBHK: 15, twoBHK: 20, threeBHK: 32 },
    commute: {
      indiranagar: 55,
      hsr: 25,
      whitefield: 75,
      electronicCity: 0,
      mgRoad: 35,
    },
    metro: 'Yellow Line — EC to Silk Board (18 min)',
    summary: 'Highest appreciation + yield in city. Lifestyle is spartan — drive out for fun.',
  },
  {
    id: 'manyata',
    name: 'Hebbal / Manyata',
    zone: 'North',
    mapX: 42,
    mapY: 22,
    tag: 'Airport corridor',
    tagline: 'Fastest growing north Bangalore',
    income: {
      jobScore: 78,
      freelanceScore: 62,
      avgSalaryLPA: { min: 10, max: 22 },
      topEmployers: ['Cognizant', 'IBM', 'Levi Strauss Tech', 'Myntra', 'Embassy Group'],
      topRoles: ['Software Engineer', 'Data', 'Marketing', 'DevOps', 'Consulting'],
      freelanceRate: '₹2–8k/day',
    },
    invest: {
      resScore: 76,
      comScore: 88,
      pricePerSqft: 9000,
      appreciation: 17,
      rentalYield: 3.8,
      avgPropertyPrice: 90,
      breakEvenYrs: 8,
      topProjects: ['Sobha Dream Gardens', 'Embassy Lake Terraces', 'Prestige Northside'],
    },
    lifestyle: {
      foodScore: 54,
      clothScore: 48,
      nightlifeScore: 35,
      foodRange: '₹200–1200/meal',
      clothRange: '₹500–3k/visit',
      vibe: 'Corporate, growing fast, clean & planned',
      topSpots: ['Orion Mall', 'Sahakara Nagar strip', 'Hebbal lake cafes'],
    },
    rent: { studio: 18, oneBHK: 22, twoBHK: 30, threeBHK: 48 },
    commute: {
      indiranagar: 35,
      hsr: 45,
      whitefield: 55,
      electronicCity: 45,
      mgRoad: 25,
    },
    metro: 'Green Line — Nagawara area (planned)',
    summary: 'Best for commercial real estate ROI. Airport access a genuine lifestyle perk.',
  },
  {
    id: 'hsr',
    name: 'HSR Layout',
    zone: 'South',
    mapX: 55,
    mapY: 65,
    tag: 'Startup belt',
    tagline: '500+ startups in a walkable grid',
    income: {
      jobScore: 76,
      freelanceScore: 84,
      avgSalaryLPA: { min: 12, max: 30 },
      topEmployers: ['Razorpay', 'Ola Electric', 'Startup ecosystem', 'WeWork co-working'],
      topRoles: ['Software Engineer', 'Product', 'Data', 'Marketing', 'Strategy'],
      freelanceRate: '₹3–12k/day',
    },
    invest: {
      resScore: 70,
      comScore: 72,
      pricePerSqft: 12000,
      appreciation: 13,
      rentalYield: 3.0,
      avgPropertyPrice: 120,
      breakEvenYrs: 10,
      topProjects: ['Salarpuria Sattva', 'Prestige units', 'Standalone 27th Main flats'],
    },
    lifestyle: {
      foodScore: 78,
      clothScore: 72,
      nightlifeScore: 75,
      foodRange: '₹300–1800/meal',
      clothRange: '₹600–4k/visit',
      vibe: 'Startup community, lively but calmer than Koramangala',
      topSpots: ['Truffles HSR', 'Byg Brewski', 'Social', '27th Main boutiques'],
    },
    rent: { studio: 20, oneBHK: 25, twoBHK: 36, threeBHK: 58 },
    commute: {
      indiranagar: 20,
      hsr: 0,
      whitefield: 65,
      electronicCity: 20,
      mgRoad: 28,
    },
    metro: 'Yellow Line — Silk Board nearby',
    summary: 'Calmer Koramangala alternative. Excellent freelance & startup ecosystem.',
  },
  {
    id: 'yeshwantpur',
    name: 'Yeshwantpur',
    zone: 'West',
    mapX: 28,
    mapY: 45,
    tag: 'Traditional west',
    tagline: 'Manufacturing & commercial ROI king',
    income: {
      jobScore: 60,
      freelanceScore: 32,
      avgSalaryLPA: { min: 5, max: 14 },
      topEmployers: ['HUL', 'Nestle India', 'Volvo India', 'ABB', 'Bosch'],
      topRoles: ['Manufacturing', 'Logistics', 'Operations', 'Software Eng (ABB)', 'Finance'],
      freelanceRate: '₹800–3k/day',
    },
    invest: {
      resScore: 65,
      comScore: 78,
      pricePerSqft: 7200,
      appreciation: 11,
      rentalYield: 3.5,
      avgPropertyPrice: 72,
      breakEvenYrs: 9,
      topProjects: ['Peenya industrial units', 'Rajajinagar ext apartments', 'Yeshwantpur commercial'],
    },
    lifestyle: {
      foodScore: 56,
      clothScore: 62,
      nightlifeScore: 28,
      foodRange: '₹60–500/meal',
      clothRange: '₹300–2k/visit',
      vibe: 'Old Bangalore, traditional, underrated value',
      topSpots: ['Udupi chains', 'CTR Malleshwaram', 'Rajajinagar 4th block', 'APMC market'],
    },
    rent: { studio: 12, oneBHK: 16, twoBHK: 22, threeBHK: 34 },
    commute: {
      indiranagar: 40,
      hsr: 40,
      whitefield: 55,
      electronicCity: 45,
      mgRoad: 18,
    },
    metro: 'Purple Line — Yeshwantpur station',
    summary: 'Best industrial & warehouse investment ROI. Classic Old Bangalore lifestyle.',
  },
  {
    id: 'sarjapur',
    name: 'Sarjapur Rd',
    zone: 'SE',
    mapX: 72,
    mapY: 76,
    tag: 'New IT corridor',
    tagline: 'Highest 5-yr appreciation in city',
    income: {
      jobScore: 74,
      freelanceScore: 60,
      avgSalaryLPA: { min: 10, max: 22 },
      topEmployers: ['Wipro SEZ', 'Amazon Dev Centre', 'RGA Tech Park', 'Cisco'],
      topRoles: ['Software Engineer', 'DevOps', 'Project Management', 'Finance', 'Real Estate'],
      freelanceRate: '₹2–7k/day',
    },
    invest: {
      resScore: 86,
      comScore: 74,
      pricePerSqft: 7800,
      appreciation: 24,
      rentalYield: 4.4,
      avgPropertyPrice: 78,
      breakEvenYrs: 6,
      topProjects: ['Provident Sunworth', 'Prestige Sarjapur', 'Godrej Properties'],
    },
    lifestyle: {
      foodScore: 60,
      clothScore: 54,
      nightlifeScore: 42,
      foodRange: '₹200–1000/meal',
      clothRange: '₹500–3k/visit',
      vibe: 'Growing fast, IT-influx, weekend mall crowd',
      topSpots: ['Forum Shantiniketan', 'ORR QSR strip', 'Carmelram cafes'],
    },
    rent: { studio: 16, oneBHK: 20, twoBHK: 26, threeBHK: 42 },
    commute: {
      indiranagar: 45,
      hsr: 30,
      whitefield: 40,
      electronicCity: 35,
      mgRoad: 40,
    },
    metro: 'Phase 3 planned — Sarjapur corridor',
    summary: 'Top investment pick in city. Buy here, live elsewhere until metro arrives.',
  },
]

export const INCOME_ROLES = [
  'Software Engineer', 'Product Manager', 'Data Scientist', 'UI/UX Designer',
  'DevOps Engineer', 'Marketing', 'Finance', 'Sales', 'Operations', 'Consulting',
]

export const SAL_BANDS = [
  { label: '₹4–8 LPA', min: 4, max: 8 },
  { label: '₹8–12 LPA', min: 8, max: 12 },
  { label: '₹12–20 LPA', min: 12, max: 20 },
  { label: '₹20–30 LPA', min: 20, max: 30 },
  { label: '₹30–45 LPA', min: 30, max: 45 },
  { label: '₹45–60 LPA', min: 45, max: 60 },
  { label: '₹60–80 LPA', min: 60, max: 80 },
  { label: '₹80+ LPA', min: 80, max: 200 },
]

export const INV_BANDS = [
  '₹30–50L', '₹50–70L', '₹70–90L', '₹90L–1.2Cr',
  '₹1.2–2Cr', '₹2–3.5Cr', '₹3.5–5Cr', '₹5Cr+',
]

export const FOOD_BANDS = [
  '₹3–5k/mo', '₹5–8k/mo', '₹8–14k/mo', '₹14–20k/mo',
  '₹20–30k/mo', '₹30–45k/mo', '₹45k+/mo',
]

export const CLOTH_BANDS = [
  '₹2–3k/mo', '₹3–6k/mo', '₹6–12k/mo', '₹12–20k/mo',
  '₹20–35k/mo', '₹35k+/mo',
]

export const ROI_TARGETS = ['8%', '10%', '12%', '15%', '18%', '22%', '26%', '30%+']

export const INV_BUDGETS = [30, 50, 70, 90, 120, 200, 350, 500]

export const PERSONAS = {
  fresher: { sal: 2, inv: 2, food: 2, cloth: 1, roi: 2, skill: 'Software Engineer', label: 'Fresh graduate' },
  midlevel: { sal: 3, inv: 3, food: 3, cloth: 3, roi: 3, skill: 'Product Manager', label: 'Mid-level professional' },
  senior: { sal: 6, inv: 6, food: 5, cloth: 5, roi: 5, skill: 'Software Engineer', label: 'Senior / lead' },
  freelancer: { sal: 3, inv: 3, food: 3, cloth: 2, roi: 3, skill: 'UI/UX Designer', label: 'Freelancer' },
  investor: { sal: 4, inv: 8, food: 2, cloth: 1, roi: 7, skill: 'Finance', label: 'Investor' },
  family: { sal: 4, inv: 5, food: 4, cloth: 3, roi: 4, skill: 'Software Engineer', label: 'Family mover' },
}
